### PR TITLE
Add async ckpt save api for colossalai plugins

### PR DESCRIPTION
**Pull request by huzixi2005**
## 📝 What does this PR do?

PyTorch Distributed Asynchronous Checkpointing reduces Model Checkpointing Times by Over 10x, async ckpt save function is necessary for LLM traing worker, so we add async ckpt save api for colossalai plugins for colossalai users.

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [ ] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by wangbluo** [comment]
Add the test for Async kept save:
Benchmark async saving and record GPU memory, system memory, and RAM cache + buffer.

**Comment by huzixi2005** [comment]
> Add the test for Async kept save: Benchmark async saving and record GPU memory, system memory, and RAM cache + buffer.

Okay.

Test config:
checkpoint benchmark
model size: 7b gpus numbers: 4; tp=2 pp=2
trace in gpu 0

use asyncio: True
image

use asyncio: False
image

**Comment by wangbluo** [comment]
Add your test script here.

**Comment by huzixi2005** [comment]
> Add your test script here.

```import psutil

def print_resource_usage(tag: str):
    """Print GPU memory, RAM, and cache/buffer usage."""
    # GPU memory usage (if CUDA is available)
    if torch.cuda.is_available():
        allocated = torch.cuda.memory_allocated()
        reserved = torch.cuda.memory_reserved()
        print(f"[{tag}] GPU Memory - Allocated: {allocated / 1024**3:.2f} GB, "
              f"Reserved: {reserved / 1024**3:.2f} GB")
    else:
        print(f"[{tag}] GPU Memory - CUDA not available")
    
    # RAM usage
    virtual_mem = psutil.virtual_memory()
    print(f"[{tag}] RAM - Total: {virtual_mem.total / 1024**3:.2f} GB, "
          f"Available: {virtual_mem.available / 1024**3:.2f} GB, "
          f"Buffers: {getattr(virtual_mem, 'buffers', 0) / 1024**3:.2f} GB, "
          f"Cached: {getattr(virtual_mem, 'cached', 0) / 1024**3:.2f} GB")```

**Pull request merged**
